// examples/solid/src/components/banner.tsx
import { ComponentProps } from "@flows/js";
import { Component } from "solid-js";

type Props = ComponentProps<{
  title: string;
  body: string;

  close: () => void;
}>;

export const Banner: Component<Props> = (props) => {
  return (
    <div>
      <h2>{props.title}</h2>
      <p>{props.body}</p>

      <button onClick={props.close}>Close</button>
    </div>
  );
};

// examples/react/tanstack/src/components/banner.tsx
import type { FC } from "react";
import { ComponentProps } from "@flows/react";

type Props = ComponentProps<{
  title: string;
  body: string;

  close: () => void;
}>;

export const Banner: FC<Props> = (props) => {
  return (
    <div>
      <p>{props.title}</p>
      <p>{props.body}</p>
      <div>
        <button onClick={props.close}>Close</button>
      </div>
    </div>
  );
};
