// workspaces/react-components/src/components/tooltip.tsx
import { type FC } from "react";
import { type Placement } from "@flows/shared";
import { BaseTooltip } from "../internal-components/base-tooltip";
import { Button } from "../internal-components/button";

export interface TooltipProps {
  title: string;
  body: string;
  continueText?: string;
  targetElement: string;
  showCloseButton: boolean;
  placement?: Placement;
  hideOverlay?: boolean;

  continue: () => void;
  close: () => void;
}

export const Tooltip: FC<TooltipProps> = (props) => {
  return (
    <BaseTooltip
      title={props.title}
      body={props.body}
      targetElement={props.targetElement}
      placement={props.placement}
      overlay={!props.hideOverlay}
      onClose={props.showCloseButton ? props.close : undefined}
      buttons={
        props.continueText ? (
          <Button variant="primary" onClick={props.continue}>
            {props.continueText}
          </Button>
        ) : null
      }
    />
  );
};

// examples/vue/nuxt-custom-components/components/flows/components/tooltip.vue
<script setup lang="ts">
const props = defineProps({
  title: {
    type: String,
    required: true,
  },
  body: {
    type: String,
    required: true,
  },
  continueText: {
    type: String,
    required: false,
  },
  previousText: {
    type: String,
    required: false,
  },
  targetElement: {
    type: String,
    required: true,
  },
  showCloseButton: {
    type: Boolean,
    required: true,
  },
  placement: {
    type: String,
    required: false,
  },
  hideOverlay: {
    type: Boolean,
    required: true,
  },

  continue: {
    type: Function,
    required: true,
  },
  close: {
    type: Function,
    required: true,
  },
});
</script>

<template>
  <div>
    Tooltip example implementation will be added in the future. You can check React component to
    implement it yourself:
    https://github.com/RBND-studio/flows-sdk/blob/main/workspaces/react-components/src/internal-components/tooltip/base-tooltip.tsx
  </div>
</template>
