// examples/react/tanstack/src/components/banner.tsx
import type { FC } from "react";
import { ComponentProps } from "@flows/react";

type Props = ComponentProps<{
  title: string;
  body: string;

  close: () => void;
}>;

export const Banner: FC<Props> = (props) => {
  return (
    <div>
      <p>{props.title}</p>
      <p>{props.body}</p>
      <div>
        <button onClick={props.close}>Close</button>
      </div>
    </div>
  );
};

// examples/vue/nuxt/app/components/banner.vue
<script setup lang="ts">
import type { ComponentProps } from "@flows/js";

type Props = ComponentProps<{
  title: string;
  body: string;

  close: () => void;
}>;

const props = defineProps<Props>();
</script>

<template>
  <div>
    <h2>{{ props.title }}</h2>
    <p>{{ props.body }}</p>

    <button @click="props.close">Close</button>
  </div>
</template>
