// examples/react/tanstack/src/components/flows.tsx
import type { FC, ReactNode } from "react";
import { Link } from "@tanstack/react-router";

import { FlowsProvider, type LinkComponentType } from "@flows/react";
import * as components from "@flows/react-components";
import * as tourComponents from "@flows/react-components/tour";
import * as surveyComponents from "@flows/react-components/survey";
import "@flows/react-components/index.css";

import { Banner } from "~/components/banner";
import { TourBanner } from "~/components/tour-banner";

type Props = {
  children: ReactNode;
};

const LinkComponent: LinkComponentType = ({ href, children, className, onClick }) => (
  <Link to={href} className={className} onClick={onClick}>
    {children}
  </Link>
);

export const Flows: FC<Props> = ({ children }) => {
  return (
    <FlowsProvider
      organizationId="YOUR_ORGANIZATION_ID"
      userId="YOUR_USER_ID"
      environment="production"
      LinkComponent={LinkComponent}
      components={{
        ...components,
        Banner: Banner,
      }}
      tourComponents={{
        ...tourComponents,
        Banner: TourBanner,
      }}
      surveyComponents={{ ...surveyComponents }}
    >
      {children}
    </FlowsProvider>
  );
};

// examples/solid/src/flows.tsx
import { onMount } from "solid-js";
import { customElement } from "solid-element";
import { useNavigate } from "@solidjs/router";

import { init } from "@flows/js";
import { setupJsComponents } from "@flows/js-components";

import * as components from "@flows/js-components/components";
import * as tourComponents from "@flows/js-components/tour-components";
import * as surveyComponents from "@flows/js-components/survey-components";

// Don't forget to import the CSS styles for Flows components
import "@flows/js-components/index.css";

import { Banner as SolidBanner } from "~/components/banner";
import { TourBanner as SolidTourBanner } from "~/components/tour-banner";

export const Flows = () => {
  const navigate = useNavigate();

  onMount(() => {
    init({
      organizationId: "YOUR_ORGANIZATION_ID",
      userId: "YOUR_USER_ID",
      environment: "production",
      onNavigate: (href, event) => {
        event.preventDefault();

        navigate(href);
      },
    });

    const Banner = customElement(
      "flows-banner",
      {
        // Define prop keys with default values
        title: "",
        body: "",
        close: () => {},
        __flows: { id: "", workflowId: "" },
      },
      SolidBanner,
    );
    const TourBanner = customElement(
      "flows-tour-banner",
      {
        // Define prop keys with default values
        title: "",
        body: "",
        previous: () => {},
        continue: () => {},
        cancel: () => {},
        __flows: { id: "", workflowId: "" },
      },
      SolidTourBanner,
    );

    setupJsComponents({
      components: {
        ...components,
        // Example of custom "Banner" component
        Banner,
      },
      tourComponents: {
        ...tourComponents,
        // Example of custom "Banner" component for tours
        Banner: TourBanner,
      },
      surveyComponents: {
        ...surveyComponents,
      },
    });
  });

  return <flows-floating-blocks />;
};
