// examples/lit/src/tour-banner.ts
import type { FlowsProperties, TourComponentProps } from "@flows/js";
import { html, LitElement } from "lit";

type Props = TourComponentProps<{
  title: string;
  body: string;
}>;

export class TourBanner extends LitElement implements Props {
  title = "";

  body = "";

  previous?: () => void;
  continue: () => void;
  cancel: () => void;

  __flows: FlowsProperties;

  render() {
    return html`
      <div>
        <p>${this.title}</p>
        <p>${this.body}</p>
        <div>
          <!-- In the first step the previous function is undefined -->
          ${this.previous && html`<button @click=${this.previous}>Previous</button>`}
          <button @click=${this.continue}>Continue</button>
          <button @click=${this.cancel}>Cancel</button>
        </div>
      </div>
    `;
  }
}

// examples/react/vite/app/components/tour-banner.tsx
import type { FC } from "react";
import type { TourComponentProps } from "@flows/react";

type Props = TourComponentProps<{
  title: string;
  body: string;
}>;

export const TourBanner: FC<Props> = (props) => {
  return (
    <div>
      <p>{props.title}</p>
      <p>{props.body}</p>
      <div>
        {/* In the first step the previous function is undefined */}
        {props.previous && <button onClick={props.previous}>Previous</button>}
        <button onClick={props.continue}>Continue</button>
        <button onClick={props.cancel}>Cancel</button>
      </div>
    </div>
  );
};
