// examples/vue/nuxt/app/components/tour-banner.vue
<script setup lang="ts">
import type { TourComponentProps } from "@flows/js";

type Props = TourComponentProps<{
  title: string;
  body: string;
}>;

const props = defineProps<Props>();
</script>

<template>
  <div>
    <h2>{{ props.title }}</h2>
    <p>{{ props.body }}</p>

    <!--  In the first step the previous function is undefined -->
    <button v-if="!!props.previous" @click="props.previous">Previous</button>
    <button @click="props.continue">Continue</button>
    <button @click="props.cancel">Cancel</button>
  </div>
</template>

// examples/react/vite/app/components/tour-banner.tsx
import type { FC } from "react";
import type { TourComponentProps } from "@flows/react";

type Props = TourComponentProps<{
  title: string;
  body: string;
}>;

export const TourBanner: FC<Props> = (props) => {
  return (
    <div>
      <p>{props.title}</p>
      <p>{props.body}</p>
      <div>
        {/* In the first step the previous function is undefined */}
        {props.previous && <button onClick={props.previous}>Previous</button>}
        <button onClick={props.continue}>Continue</button>
        <button onClick={props.cancel}>Cancel</button>
      </div>
    </div>
  );
};
